# Generated by Django 3.2.7 on 2021-11-06 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Wine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('puntuacion', models.FloatField()),
                ('precio', models.FloatField()),
            ],
            options={
                'db_table': 'wines',
            },
        ),
    ]
