# Generated by Django 3.2.7 on 2021-11-11 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wines', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wine',
            old_name='precio',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='wine',
            old_name='puntuacion',
            new_name='score',
        ),
    ]
